openapi: 3.0.3
info:
  title: OpenTripMap (minimal)
  version: "0.1.0"
  description: Minimal OTM surface for travel itinerary agents.
servers:
  - url: https://api.opentripmap.com/0.1
components:
  parameters:
    LangParam:
      name: lang
      in: path
      required: true
      schema: { type: string, default: en }
  securitySchemes:
    ApiKeyQuery:
      type: apiKey
      in: query
      name: apikey
paths:
  "/{lang}/places/radius":
    get:
      operationId: otmPlacesRadius
      summary: List places within a radius
      parameters:
        - $ref: '#/components/parameters/LangParam'
        - { name: lat, in: query, required: true, schema: { type: number, format: float } }
        - { name: lon, in: query, required: true, schema: { type: number, format: float } }
        - { name: radius, in: query, required: true, schema: { type: integer, minimum: 1, maximum: 50000 } }
        - { name: kinds, in: query, required: false, schema: { type: string }, description: "Comma-separated categories" }
        - { name: limit, in: query, required: false, schema: { type: integer, default: 20, maximum: 500 } }
        - { name: format, in: query, required: false, schema: { type: string, enum: [json, geojson], default: json } }
      responses:
        "200":
          description: OK
          content: { application/json: { schema: { type: object } } }

  "/{lang}/places/xid/{xid}":
    get:
      operationId: otmPlaceDetails
      summary: Get details for a place by XID
      parameters:
        - $ref: '#/components/parameters/LangParam'
        - { name: xid, in: path, required: true, schema: { type: string } }
      responses:
        "200":
          description: OK
          content: { application/json: { schema: { type: object } } }

  "/{lang}/places/geoname":
    get:
      operationId: otmGeoname
      summary: Resolve a placename to coordinates
      parameters:
        - $ref: '#/components/parameters/LangParam'
        - { name: name, in: query, required: true, schema: { type: string } }
        - { name: country, in: query, required: false, schema: { type: string, minLength: 2, maxLength: 2 } }
      responses:
        "200": { description: OK, content: { application/json: { schema: { type: object } } } }

  "/{lang}/places/autosuggest":
    get:
      operationId: otmAutosuggest
      summary: Autosuggest places near a point
      parameters:
        - $ref: '#/components/parameters/LangParam'
        - { name: name, in: query, required: true, schema: { type: string } }
        - { name: lon, in: query, required: false, schema: { type: number, format: float } }
        - { name: lat, in: query, required: false, schema: { type: number, format: float } }
        - { name: radius, in: query, required: false, schema: { type: integer } }
        - { name: kinds, in: query, required: false, schema: { type: string } }
        - { name: limit, in: query, required: false, schema: { type: integer, default: 10 } }
      responses:
        "200": { description: OK, content: { application/json: { schema: { type: object } } } }

# Optional (documentary only; auth is configured in Gateway):
security:
  - ApiKeyQuery: []
